server:
  port: ${PORT:8762}
  max-http-request-header-size: 16KB

# Configuración de Eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: ${HOSTNAME:localhost}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

# Configuración principal del API Gateway
spring:
  application:
    name: gateway-acl
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ms-books-catalogue
          uri: lb://ms-books-catalogue
          predicates:
            - Path=/api/libros/**
          filters:
            - StripPrefix=0

        - id: ms-books-payments
          uri: lb://ms-books-payments
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=0

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:*}
            allowedHeaders: "*"
            allowedMethods:
              - POST
              - GET
              - PUT
              - DELETE
              - PATCH

# Actuator para monitoreo y ver rutas activas
management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - '*'
